- name: Create instance(s)
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    machine_type: n1-standard-1 # default
    image: debian-7
    service_account_email: ansible@keen-clarity-231522.iam.gserviceaccount.com
    credentials_file: /Users/pacocampo/Downloads/keen-clarity-231522-b0476898d9e7.json
    project_id: keen-clarity-231522

  tasks:
    - name: Launch instances
      gce:
          instance_names: dev
          machine_type: "{{ machine_type }}"
          image: "{{ image }}"
          service_account_email: ansible@keen-clarity-231522.iam.gserviceaccount.com
          credentials_file: /Users/pacocampo/Downloads/keen-clarity-231522-b0476898d9e7.json
          project_id: keen-clarity-231522
          tags: webserver
      register: gce

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
      loop: "{{ gce.instance_data }}"

    - name: Add host to groupname
      add_host: hostname={{ item.public_ip }} groupname=new_instances
      loop: "{{ gce.instance_data }}"
